### PR TITLE
Implement Kubernetes Support

### PR DESCRIPTION
**Pull request by RealistikDash**
This PR aims to introduce the **option** of running RealistikGDPS inside a Kubernetes cluster.

## Objectives
- [x] Create a RealistikGDPS release on Docker Hub.
- [x] Create Kubernetes Deployment and External Service for RealistikGDPS.
- [ ] Implement a suitable way of doing configurations
- [ ] Test with multiple replicas
- [ ] Ensure all other deployment methods (standalone, compose) still work.

### CODE REVIEW

**Comment by cmyui** [comment]
He is cooking

**Comment by tsunyoku** [comment]
No

**Comment by RealistikDash** [comment]
On hold until the project is more deployable ig.

**Comment by RealistikDash** [comment]
Closed, too out of date for the current project. Will be remade eventually.

**Comment by cmyui** [comment]
If u wanna try it again, lemme show u helm in jp

**Comment by cmyui** [comment]
It's op

**Comment by RealistikDash** [comment]
Bet

**Pull request closed without merging**
