### PR TITLE
fix: increase char limit on song names

### PR DESCRIPTION
**Pull request by 7ez**
this fixes upload failed for levels like [Sunshine](https://gdbrowser.com/56199846) which have a long song name.

### CODE REVIEW

**Review by RealistikDash — CHANGES_REQUESTED** [review]
Make these an hp and down migration.

**Comment by 7ez** [comment]
> Make these an hp and down migration.

Wouldn't that delete the song names entirely.

**Comment by RealistikDash** [comment]
Idk but convention

**Review by RealistikDash — APPROVED** [review]
Lgtm!

**Pull request merged**
